---
- name: Install GitLab Runner (official repository)
  block:
    - name: Download GitLab Runner GPG key
      ansible.builtin.get_url:
        url: https://packages.gitlab.com/gpg.key
        dest: /tmp/gitlab-runner.gpg
        mode: '0644'
      become: true

    - name: Dearmor and install GitLab Runner GPG key
      ansible.builtin.shell: gpg --dearmor -o /usr/share/keyrings/gitlab-runner.gpg /tmp/gitlab-runner.gpg
      args:
        creates: /usr/share/keyrings/gitlab-runner.gpg
        removes: /tmp/gitlab-runner.gpg
      become: true

    - name: Add GitLab Runner APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/gitlab-runner.gpg] https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ ansible_distribution_release }} main"
        state: present
        filename: gitlab-runner
        update_cache: yes

    - name: Install GitLab Runner
      ansible.builtin.apt:
        name: gitlab-runner
        state: present
        update_cache: yes

- name: Register GitLab Docker Runner
  ansible.builtin.command: >
    gitlab-runner register
    --non-interactive
    --url "https://gitlab.com/"
    --registration-token "{{ gitlab_runner_registration_token }}"
    --executor "docker"
    --docker-image alpine:latest
    --description "docker-runner"
    --run-untagged="false"
    --locked="true"
    --access-level="ref_protected"
  register: docker_runner_registration
  changed_when: "'Runner registered successfully' in docker_runner_registration.stdout"
  when: gitlab_runner_registration_token is defined and gitlab_runner_registration_token is not none and gitlab_runner_registration_token | length > 0

