---
- name: Setup GitLab Runner
  hosts: all
  become: true
  vars_files:
    - ./secrets.yml

  roles:
    - role: geerlingguy.docker
      tags: docker

  tasks:
    - name: Install and configure GitLab Runner
      ansible.builtin.include_tasks: tasks/gitlab-runner.yml
      tags: gitlab-runner
